version: '3.7'
services:
    db:
        image: 'mysql:8'
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        volumes:
            - ./.docker/mysql/config/mysql-docker.cnf:/etc/mysql/conf.d/mysql-docker.cnf:ro
            - ./.docker/mysql/config/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql:ro
            - ./.docker/mysql/data/:/var/lib/mysql:rw
            - ./.docker/mysql/log/:/var/log/mysql:rw
        restart: always
        ports:
            # To allow the host machine to access the ports below, modify the lines below.
            # For example, to allow the host to connect to port 3306 on the container, you would change
            # "3306" to "3306:3306". Where the first port is exposed to the host and the second is the container port.
            # See https://docs.docker.com/compose/compose-file/#ports for more information.
            - '3306:3306'
    apache:
        build: ./.docker/apache
        ports:
            - 8080:80
        volumes:
            - ./public:/var/www/html/public:ro
            - ./.docker/apache/config/vhosts.conf:/etc/apache2/sites-enabled/vhosts.conf:ro
        depends_on:
            - php
    php:
        build:
            context: .
            dockerfile: ./.docker/php/Dockerfile
        environment:
            APP_ENV: ${APP_ENV}
            MYSQL_HOST: db
            MYSQL_PORT: 3306
        volumes:
            - .:/var/www/html:rw
            - ./.docker/php/logs:/app/var/logs:rw
        depends_on:
            - db
    phpmyadmin:
        image: phpmyadmin
        restart: always
        ports:
            - 8005:80
        environment:
            PMA_HOST: db
        